apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ecocycle-backend
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: ecocycle-backend
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: "8080"
      path: /actuator/prometheus
      interval: 15s
